title: The Distributed Engineer’s TIL
description: Practical patterns and architectural deep dives.
remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "10"

color_scheme: nil
dark_mode: true

search_enabled: true
