title: Handbook
description: "Battle-tested patterns and architectural decisions by Michał Śnieżko."

remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "10"

color_scheme: light

search_enabled: true

footer_content: "Copyright &copy; 2026 Michał Śnieżko. Distributed Engineer's Handbook."

aux_links:
  "LinkedIn":
    - "https://linkedin.com/in/michal-sniezko"

favicon_ico: "/favicon.ico"
