title: The Distributed Engineer’s TIL
description: Practical patterns and architectural deep dives.
remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "10"

color_scheme: light

search_enabled: true

footer_content: "Copyright &copy; 2026 Michał Śnieżko. Distributed Engineer's TIL blog."

aux_links:
  "GitHub":
    - "https://github.com/michalsniezko"
  "LinkedIn":
    - "https://linkedin.com/in/michal-sniezko"

